Search:
	party.cpp polymorph.cpp priv_manager.cpp pvp.cpp\

Change:
	party.cpp polymorph.cpp Deathmatch.cpp priv_manager.cpp pvp.cpp\




Search:
	questlua_quest.cpp questlua_target.cpp questmanager.cpp questnpc.cpp questpc.cpp\

Change:
	questlua_quest.cpp questlua_target.cpp questmanager.cpp questlua_deathmatch.cpp questnpc.cpp questpc.cpp\
