//Find:
enum SPECIAL_EFFECT
//Add below(up to it):
#ifdef ITEM_BUFF_SYSTEM
enum EItemBuffConfig
{
	
//first item resist buff config	
	MASTER_RESIST_BLESS_ITEM_BUFF_VNUM = 79000,
	MASTER_RESIST_BLESS_AFFECT_VALUE = 24,
	MASTER_RESIST_BLESS_AFFECT_TIME_VALUE = 160,	
	MASTER_RESIST_BLESS_USINGS = 80,
// end of first item resist buff config

//secound item resist buff config	
	GRAND_RESIST_BLESS_ITEM_BUFF_VNUM = 79001,
	GRAND_RESIST_BLESS_AFFECT_VALUE = 29,
	GRAND_RESIST_BLESS_AFFECT_TIME_VALUE = 224,	
	GRAND_RESIST_BLESS_USINGS = 60,
//end of second item resist buff config	

//third item resist buff config	
	PERFECT_RESIST_BLESS_ITEM_BUFF_VNUM = 79002,
	PERFECT_RESIST_BLESS_AFFECT_VALUE = 35,
	PERFECT_RESIST_BLESS_AFFECT_TIME_VALUE = 310,	
	PERFECT_RESIST_BLESS_USINGS = 50,
//end of third item resist buff config	

//first item critical buff config
	MASTER_CRITICAL_BLESS_ITEM_BUFF_VNUM = 79003,
	MASTER_CRITICAL_BLESS_AFFECT_VALUE = 24,
	MASTER_CRITICAL_BLESS_AFFECT_TIME_VALUE = 110,	
	MASTER_CRITICAL_BLESS_USINGS = 80,
//end of first item critical buff config

//secound item critical buff config	
	GRAND_CRITICAL_BLESS_ITEM_BUFF_VNUM = 79004,
	GRAND_CRITICAL_BLESS_AFFECT_VALUE = 29,
	GRAND_CRITICAL_BLESS_AFFECT_TIME_VALUE = 142,	
	GRAND_CRITICAL_BLESS_USINGS = 60,
//end of secound item critical buff config	

//third item critical buff config
	PERFECT_CRITICAL_BLESS_ITEM_BUFF_VNUM = 79005,
	PERFECT_CRITICAL_BLESS_AFFECT_VALUE = 35,
	PERFECT_CRITICAL_BLESS_AFFECT_TIME_VALUE = 185,	
	PERFECT_CRITICAL_BLESS_USINGS = 50,	
//end of third item critical buff config	

//first item reflection buff config
	MASTER_REFLECT_BLESS_ITEM_BUFF_VNUM = 79006,
	MASTER_REFLECT_BLESS_AFFECT_VALUE = 21,
	MASTER_REFLECT_BLESS_AFFECT_TIME_VALUE = 160,	
	MASTER_REFLECT_BLESS_USINGS = 80,
//end of first item reflection buff config

//secound item reflection buff config	
	GRAND_REFLECT_BLESS_ITEM_BUFF_VNUM = 79007,
	GRAND_REFLECT_BLESS_AFFECT_VALUE = 31,
	GRAND_REFLECT_BLESS_AFFECT_TIME_VALUE = 224,	
	GRAND_REFLECT_BLESS_USINGS = 60,
//end of secound item reflection buff config	

//third item reflection buff config
	PERFECT_REFLECT_BLESS_ITEM_BUFF_VNUM = 79008,
	PERFECT_REFLECT_BLESS_AFFECT_VALUE = 45,
	PERFECT_REFLECT_BLESS_AFFECT_TIME_VALUE = 310,	
	PERFECT_REFLECT_BLESS_USINGS = 50,	
//end of third item reflection buff config	

};
#endif
