if pc . get_level ( ) < 40 then 
say_title ( gameforge . deviltower_zone . _20_sayTitle ) 
say ( gameforge . deviltower_zone . _30_say ) 
else 
say_title ( gameforge . deviltower_zone . _20_sayTitle ) 
say ( gameforge . deviltower_zone . _40_say ) 
local s = select ( gameforge . locale . monkey_dungeon . enter , gameforge . locale . monkey_dungeon . no_enter ) 
if s == 1 then 
pc . warp ( 216500 , 727000 ) 
end 
end 
