Cauta -------

case DRAGON_SOUL_INVENTORY:

Adauga sub -------

#ifdef WJ_SPLIT_INVENTORY_SYSTEM
				case SKILL_BOOK_INVENTORY:
				case UPGRADE_ITEMS_INVENTORY:
				case STONE_INVENTORY:
				case SANDIK_INVENTORY:
#endif