ARATILIR ---------------

SHOP_TAB_COUNT_MAX = 3,  

ALTINA EKLE -------------,

#ifdef WJ_SPLIT_INVENTORY_SYSTEM
	SKILL_BOOK_INVENTORY_MAX_NUM	= 135,
	UPGRADE_ITEMS_INVENTORY_MAX_NUM	= 135,
	STONE_INVENTORY_MAX_NUM	= 135,
	SANDIK_INVENTORY_MAX_NUM	= 135,
#endif


ARATILIR --------- 

BELT_INVENTORY,

ALTINA EKLE -------------,

#ifdef WJ_SPLIT_INVENTORY_SYSTEM
	SKILL_BOOK_INVENTORY,
	UPGRADE_ITEMS_INVENTORY,
	STONE_INVENTORY,
	SANDIK_INVENTORY,
#endif

ARATILIR --------- 

BELT_INVENTORY_SLOT_END = BELT_INVENTORY_SLOT_START + BELT_INVENTORY_SLOT_COUNT,

ALTINA EKLE -------------,

#ifdef WJ_SPLIT_INVENTORY_SYSTEM
	SKILL_BOOK_INVENTORY_SLOT_START	= BELT_INVENTORY_SLOT_END,
	SKILL_BOOK_INVENTORY_SLOT_END = SKILL_BOOK_INVENTORY_SLOT_START + SKILL_BOOK_INVENTORY_MAX_NUM,
	
	UPGRADE_ITEMS_INVENTORY_SLOT_START = SKILL_BOOK_INVENTORY_SLOT_END,
	UPGRADE_ITEMS_INVENTORY_SLOT_END = UPGRADE_ITEMS_INVENTORY_SLOT_START + UPGRADE_ITEMS_INVENTORY_MAX_NUM,
	
	STONE_INVENTORY_SLOT_START = UPGRADE_ITEMS_INVENTORY_SLOT_END,
	STONE_INVENTORY_SLOT_END = STONE_INVENTORY_SLOT_START + STONE_INVENTORY_MAX_NUM,
	
	SANDIK_INVENTORY_SLOT_START = STONE_INVENTORY_SLOT_END,
	SANDIK_INVENTORY_SLOT_END = SANDIK_INVENTORY_SLOT_START + SANDIK_INVENTORY_MAX_NUM,
#endif

#ifdef WJ_SPLIT_INVENTORY_SYSTEM
	//INVENTORY_AND_EQUIP_SLOT_MAX = UPGRADE_ITEMS_INVENTORY_SLOT_END,
	INVENTORY_AND_EQUIP_SLOT_MAX = SANDIK_INVENTORY_SLOT_END,
#else
	INVENTORY_AND_EQUIP_SLOT_MAX = BELT_INVENTORY_SLOT_END,
#endif

ARATILIR --------- 

case BELT_INVENTORY:

ALTINA EKLE -------------,

#ifdef WJ_SPLIT_INVENTORY_SYSTEM
		case SKILL_BOOK_INVENTORY:
		case UPGRADE_ITEMS_INVENTORY:
		case STONE_INVENTORY:
		case SANDIK_INVENTORY:
#endif

ARATILIR --------- 

bool IsDefaultInventoryPosition() const

ALTINA EKLE -------------,

#ifdef WJ_SPLIT_INVENTORY_SYSTEM
	bool IsSkillBookInventoryPosition() const
	{
		return ((INVENTORY == window_type) && cell >= SKILL_BOOK_INVENTORY_SLOT_START && cell < SKILL_BOOK_INVENTORY_SLOT_END);
	}
	bool IsUpgradeItemsInventoryPosition() const
	{
		return ((INVENTORY == window_type) && cell >= UPGRADE_ITEMS_INVENTORY_SLOT_START && cell < UPGRADE_ITEMS_INVENTORY_SLOT_END);
	}
	bool IsStoneInventoryPosition() const
	{
		return ((INVENTORY == window_type) && cell >= STONE_INVENTORY_SLOT_START && cell < STONE_INVENTORY_SLOT_END);
	}
	bool IsSandikInventoryPosition() const
	{
		return ((INVENTORY == window_type) && cell >= SANDIK_INVENTORY_SLOT_START && cell < SANDIK_INVENTORY_SLOT_END);
	}
#endif

ARATILIR --------- 

ALTINA EKLE -------------,