say_title ( gameforge . find_squareguard . _10_targetVid ) 
say ( gameforge . guild_manage . _120_say ) 
local s = select ( gameforge . locale . guild . yes , gameforge . locale . guild . no ) 
if s == 1 then 
say_title ( gameforge . find_squareguard . _10_targetVid ) 
say ( gameforge . guild_manage . _130_say ) 
pc . remove_from_guild ( ) 
pc . setqf ( "new_withdraw_time" , get_global_time ( ) ) 
end 
